-- =====================================================================
--  NICC Campus Ministry — complete Supabase schema
--  Replaces the legacy CSV datastore (backend/data/*.csv).
--
--  HOW TO USE
--    Dashboard > SQL Editor > New query > paste this whole file > Run.
--    Everything is idempotent (IF NOT EXISTS), so re-running is safe.
--
--  WHAT THIS CREATES (9 tables)
--    users               disciple/member accounts   (was users.csv)
--    admins              staff logins               (was admins.csv)
--    visitors            "Plan a Visit" leads       (was visitors.csv)
--    sign_ins            login audit trail          (was sign_ins.csv)
--    messages            contact-form messages      (was messages.csv)
--    feedback            in-portal feedback         (was feedback.csv)
--    announcements       admin broadcasts          (was announcements.csv)
--    announcement_reads  per-disciple read state    (replaces user_ids JSON)
--    verification_codes  signup/portal OTP codes    (was verification_codes.csv)
-- =====================================================================


-- =====================================================================
-- 1. USERS — disciple / member accounts
-- =====================================================================
-- Replaces users.csv: name,email,password,campus,is_verified
--
-- `password_hash` holds a BCRYPT hash generated by the backend. Plaintext
-- passwords are never sent to the database and never stored anywhere.
-- Email is stored lower-cased and UNIQUE; the functional index below also
-- stops 'A@x.com' and 'a@x.com' from coexisting.
create table if not exists public.users (
    id            uuid        primary key default gen_random_uuid(),
    email         text        not null,
    name          text        not null default 'Disciple',
    password_hash text        not null,
    campus        text,
    is_verified   boolean     not null default false,
    role          text        not null default 'disciple',
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    constraint users_email_format_chk   check (email = lower(btrim(email))),
    constraint users_email_not_blank_chk check (length(btrim(email)) > 3),
    constraint users_role_chk          check (role in ('disciple', 'leader', 'admin'))
);

create unique index if not exists users_email_lower_key on public.users (lower(email));
create index        if not exists users_verified_idx  on public.users (is_verified);

-- =====================================================================
-- 2. ADMINS — staff logins (deliberately a separate table)
-- =====================================================================
-- Replaces admins.csv: username,email,name,password
-- Kept apart from `users` so the public signup path can never mint an admin
-- row. The backend seeds the first admin from ADMIN_EMAIL/ADMIN_PASSWORD.
create table if not exists public.admins (
    id            uuid        primary key default gen_random_uuid(),
    username      text        not null,
    email         text        not null,
    name          text        not null default 'Admin',
    password_hash text        not null,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    constraint admins_email_format_chk check (email = lower(btrim(email)))
);

create unique index if not exists admins_email_lower_key on public.admins (lower(email));
create unique index if not exists admins_username_key    on public.admins (lower(username));

-- =====================================================================
-- 3. VISITORS — "Plan a Visit" submissions from /contact
-- =====================================================================
-- Replaces visitors.csv: id,date,name,email,phone,campus,status
create table if not exists public.visitors (
    id         uuid        primary key default gen_random_uuid(),
    name       text        not null,
    email      text        not null,
    phone      text,
    campus     text,
    message    text,
    status     text        not null default 'Pending Follow-up',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint visitors_status_chk check (
        status in ('Pending Follow-up', 'Contacted', 'Followed Up', 'Closed')
    )
);

create index if not exists visitors_created_at_idx on public.visitors (created_at desc);
create index if not exists visitors_status_idx     on public.visitors (status);


-- =====================================================================
-- 4. SIGN_INS — who signed in, and when
-- =====================================================================
-- Replaces sign_ins.csv: timestamp,name,email
-- Written only after an OTP has been verified. Passwords are never stored.
create table if not exists public.sign_ins (
    id         uuid        primary key default gen_random_uuid(),
    user_id    uuid        references public.users (id) on delete set null,
    name       text        not null,
    email      text        not null,
    created_at timestamptz not null default now()
);

create index if not exists sign_ins_created_at_idx on public.sign_ins (created_at desc);
create index if not exists sign_ins_email_idx      on public.sign_ins (lower(email));


-- =====================================================================
-- 5. MESSAGES — free-text contact messages
-- =====================================================================
-- Replaces messages.csv: date,name,email,message
create table if not exists public.messages (
    id         uuid        primary key default gen_random_uuid(),
    name       text        not null,
    email      text        not null,
    message    text        not null,
    is_read    boolean     not null default false,
    created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages (created_at desc);


-- =====================================================================
-- 6. FEEDBACK — in-portal feedback (prayer / suggestion / message)
-- =====================================================================
-- Replaces feedback.csv: timestamp,email,name,category,message
create table if not exists public.feedback (
    id         uuid        primary key default gen_random_uuid(),
    user_id    uuid        references public.users (id) on delete set null,
    name       text,
    email      text,
    category   text        not null default 'Message',
    message    text        not null,
    created_at timestamptz not null default now(),


-- =====================================================================
-- 7. ANNOUNCEMENTS — admin broadcasts
-- =====================================================================
-- Replaces announcements.csv: id,message_text,created_at,user_ids
create table if not exists public.announcements (
    id         uuid        primary key default gen_random_uuid(),
    message    text        not null,
    created_by uuid        references public.admins (id) on delete set null,
    created_at timestamptz not null default now(),
    constraint announcements_length_chk check (length(btrim(message)) between 1 and 1000)
);

create index if not exists announcements_created_at_idx on public.announcements (created_at desc);


-- =====================================================================
-- 8. ANNOUNCEMENT_READS — per-disciple read state
-- =====================================================================
-- The CSV stored read receipts as a JSON array inside one cell (user_ids),
-- which cannot be queried or constrained. This normalises them into rows.
--
-- MIGRATION NOTE: the old CSV receipts were keyed by
-- 'disciple-' || hex(lower(email)) — NOT a users.id. They cannot be matched
-- to this table by id. When migrating, re-key them by looking the email up
-- in public.users and inserting the correct user_id.
create table if not exists public.announcement_reads (
    announcement_id uuid        not null references public.announcements (id) on delete cascade,
    user_id         uuid        not null references public.users (id) on delete cascade,
    read_at         timestamptz not null default now(),
    primary key (announcement_id, user_id)
);

create index if not exists announcement_reads_user_idx on public.announcement_reads (user_id);


-- =====================================================================
-- 9. VERIFICATION_CODES — signup / portal-unlock OTP codes
-- =====================================================================
-- Replaces verification_codes.csv:
--   id,email,purpose,code_hash,expires_at,consumed_at,created_at
--
-- Only a SHA-256 HASH of the code is stored, never the code itself.
-- `consumed_at` is set on use so a code cannot be replayed.
create table if not exists public.verification_codes (
    id          uuid        primary key default gen_random_uuid(),
    email       text        not null,
    purpose     text        not null,
    code_hash   text        not null,
    expires_at  timestamptz not null,
    consumed_at timestamptz,
    created_at  timestamptz not null default now(),
    constraint verification_purpose_chk check (purpose in ('signup', 'portal', 'reset'))
);

create index if not exists verification_codes_lookup_idx
    on public.verification_codes (lower(email), purpose, expires_at desc);
create index if not exists verification_codes_created_at_idx
    on public.verification_codes (created_at);


-- =====================================================================
-- 10. updated_at trigger
-- =====================================================================
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists users_touch_updated_at    on public.users;
drop trigger if exists admins_touch_updated_at   on public.admins;
drop trigger if exists visitors_touch_updated_at on public.visitors;

create trigger users_touch_updated_at
    before update on public.users


-- =====================================================================
-- 11. Row Level Security
-- =====================================================================
-- The Node backend connects with the PUBLISHABLE (anon) key, so RLS applies
-- to it. The policies below grant exactly what the API needs and nothing
-- more. Do NOT switch the backend to the service_role key: it bypasses RLS
-- entirely, so a leak would expose the whole database.
--
-- There is deliberately NO delete policy on any table except
-- announcement_reads. The anon key can read, insert and update, but never
-- destroy data. Add a delete policy only if you build a "delete my
-- account" feature.
--
-- This is doing real work, not ceremony: these tables hold real personal
-- data (names, emails, phone numbers, prayer requests).
alter table public.users              enable row level security;
alter table public.admins             enable row level security;
alter table public.visitors           enable row level security;
alter table public.sign_ins           enable row level security;
alter table public.messages           enable row level security;
alter table public.feedback           enable row level security;
alter table public.announcements      enable row level security;
alter table public.announcement_reads enable row level security;
alter table public.verification_codes enable row level security;

-- users
drop policy if exists "backend can read users"   on public.users;
drop policy if exists "backend can insert users" on public.users;
drop policy if exists "backend can update users" on public.users;
create policy "backend can read users"   on public.users for select to anon using (true);
create policy "backend can insert users" on public.users for insert to anon with check (true);
create policy "backend can update users" on public.users for update to anon using (true) with check (true);



-- sign_ins (append-only: a sign-in record is never edited)
drop policy if exists "backend can read sign_ins"   on public.sign_ins;
drop policy if exists "backend can insert sign_ins" on public.sign_ins;
create policy "backend can read sign_ins"   on public.sign_ins for select to anon using (true);
create policy "backend can insert sign_ins" on public.sign_ins for insert to anon with check (true);

-- messages
drop policy if exists "backend can read messages"   on public.messages;
drop policy if exists "backend can insert messages" on public.messages;
drop policy if exists "backend can update messages" on public.messages;
create policy "backend can read messages"   on public.messages for select to anon using (true);
create policy "backend can insert messages" on public.messages for insert to anon with check (true);
create policy "backend can update messages" on public.messages for update to anon using (true) with check (true);

-- feedback
drop policy if exists "backend can read feedback"   on public.feedback;
drop policy if exists "backend can insert feedback" on public.feedback;
drop policy if exists "backend can update feedback" on public.feedback;
create policy "backend can read feedback"   on public.feedback for select to anon using (true);
create policy "backend can insert feedback" on public.feedback for insert to anon with check (true);
create policy "backend can update feedback" on public.feedback for update to anon using (true) with check (true);

-- announcements
drop policy if exists "backend can read announcements"   on public.announcements;
drop policy if exists "backend can insert announcements" on public.announcements;
drop policy if exists "backend can update announcements" on public.announcements;
create policy "backend can read announcements"   on public.announcements for select to anon using (true);
create policy "backend can insert announcements" on public.announcements for insert to anon with check (true);
create policy "backend can update announcements" on public.announcements for update to anon using (true) with check (true);

-- announcement_reads
drop policy if exists "backend can read announcement_reads"   on public.announcement_reads;
drop policy if exists "backend can insert announcement_reads" on public.announcement_reads;
drop policy if exists "backend can delete announcement_reads" on public.announcement_reads;
create policy "backend can read announcement_reads"   on public.announcement_reads for select to anon using (true);
create policy "backend can insert announcement_reads" on public.announcement_reads for insert to anon with check (true);
-- This single delete is required: a disciple dismissing a notification removes
-- their own receipt row, scoped to that row by the foreign key.
create policy "backend can delete announcement_reads" on public.announcement_reads for delete to anon using (true);

-- verification_codes
drop policy if exists "backend can read verification_codes"   on public.verification_codes;
drop policy if exists "backend can insert verification_codes" on public.verification_codes;
drop policy if exists "backend can update verification_codes" on public.verification_codes;
create policy "backend can read verification_codes"   on public.verification_codes for select to anon using (true);
create policy "backend can insert verification_codes" on public.verification_codes for insert to anon with check (true);
create policy "backend can update verification_codes" on public.verification_codes for update to anon using (true) with check (true);


-- =====================================================================
-- 12. Verification — this should list exactly the 9 tables above
-- =====================================================================
select table_name
from information_schema.tables
where table_schema = 'public'
order by table_name;

-- admins
drop policy if exists "backend can read admins"   on public.admins;
drop policy if exists "backend can insert admins" on public.admins;
drop policy if exists "backend can update admins" on public.admins;
create policy "backend can read admins"   on public.admins for select to anon using (true);
create policy "backend can insert admins" on public.admins for insert to anon with check (true);
create policy "backend can update admins" on public.admins for update to anon using (true) with check (true);

-- visitors
drop policy if exists "backend can read visitors"   on public.visitors;
drop policy if exists "backend can insert visitors" on public.visitors;
drop policy if exists "backend can update visitors" on public.visitors;
create policy "backend can read visitors"   on public.visitors for select to anon using (true);
create policy "backend can insert visitors" on public.visitors for insert to anon with check (true);
create policy "backend can update visitors" on public.visitors for update to anon using (true) with check (true);

    for each row execute function public.touch_updated_at();

create trigger admins_touch_updated_at
    before update on public.admins
    for each row execute function public.touch_updated_at();

create trigger visitors_touch_updated_at
    before update on public.visitors
    for each row execute function public.touch_updated_at();

    constraint feedback_category_chk check (
        category in ('Prayer Request', 'Suggestion', 'Message')
    )
);

create index if not exists feedback_created_at_idx on public.feedback (created_at desc);



